[build]
  publish = "frontend/dist"
  command = "cd frontend && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.admin]
  publish = "admin/dist"
  command = "cd admin && npm run build"

[context.admin.redirects]
  from = "/*"
  to = "/index.html"
  status = 200
