# Frontend build configuration
[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

# SPA routing redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
