[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.admin]
  base = "admin"
  publish = "dist"
  command = "npm run build"

[context.admin.redirects]
  from = "/*"
  to = "/index.html"
  status = 200
