# Admin Panel Build Configuration
[build]
  publish = "admin/dist"
  command = "cd admin && npm install && npm run build"

# SPA routing redirects for admin
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
